### ISSUE TITLE
requesting checkpoint

### ISSUE THREAD

**Issue by ajaysurya1221** [trusthlt/mining-legal-arguments#2]
Hey @habernal, I'm having trouble training your model as I can't afford a GPU right now, is there any way I could get your best checkpoint for testing, please? through a drive link or something?

**Comment by habernal** [comment]
@dfa30 Is it something we can easily upload somewhere, Daniel?

**Comment by habernal** [comment]
@ajaysurya1221 Apologies for the delay (summer break), we're looking for an option to host large files in a long-term repository at our university

**Comment by habernal** [comment]
It took some time, but all the models are now freely (and permanently) available at

https://tudatalib.ulb.tu-darmstadt.de/handle/tudatalib/3601?locale-attribute=en

which is now also linked in the readme. Hope it helps!
