### ISSUE TITLE
Question about loading checkpoint

### ISSUE THREAD

**Issue by dxbdxx** [trusthlt/mining-legal-arguments#3]
Hi, I am running _evaluate.py_ using the model downloaded from https://tudatalib.ulb.tu-darmstadt.de/handle/tudatalib/3601?locale-attribute=en. I have change the _models_ argument to be ['./supplementary-material/multitask-models/roberta-large-fp-15000/checkpoint-143334/roberta']. But an error is raised: 

> RuntimeError: PytorchStreamReader failed reading zip archive: not a ZIP archive 

in torch.load(model). Here, model='./supplementary-material/multitask-models/roberta-large-fp-15000/checkpoint-143334/roberta'.
Any ideas about this error?

**Comment by habernal** [comment]
@dfa30 : Daniel, can you please have a look at it, e.g., by extending the README?

**Comment by dfa30** [comment]
It seems like something went wrong with our data upload and the file is corrupted. We'll look into it and try to fix the data. 
Did you also try other models and, if you did, are these working?

**Comment by dxbdxx** [comment]
Thank you for your reply. I also tried to load the models in _supplementary-material/multitask-models/_ with torch.load(). But all the files named _roberta_ are failed to load. Here is my python packages: python3.8, torch1.12.1+cu116.

**Comment by habernal** [comment]
So it seems something went wrong when publishing the files, some ended up truncated. We're about to fix that.

**Comment by jacinthes** [comment]
Hey, has this issue been resolved? Seeing the same error on my side. Thanks.

**Comment by habernal** [comment]
Apologies for taking it so long. We're trying to publish the 70 GB file on our university premises but it's getting complicated. We're on it!

**Comment by habernal** [comment]
We've reuploaded our complete checkpoints, they are available temporarily at

https://public.ukp.informatik.tu-darmstadt.de/ih/legal-argument-mining-models/

They will be also moved to the TU-Datalib folder (as in readme).

Does it work now like that?

**Comment by habernal** [comment]
We've also replaced the checkpoints at the TU-Datalib server as pointed out in the README

https://tudatalib.ulb.tu-darmstadt.de/handle/tudatalib/3601

Hopefully everything is fine by now, closing this issue

**Comment by Yyy11181** [comment]
hello,can the checkpoint  be used in Chinese legal text?

**Comment by habernal** [comment]
It can be used for any text, but I doubt it will do anything meaningful in Chinese.
