### ISSUE TITLE
Question regarding annotation on argument level

### ISSUE THREAD

**Issue by abdullahalzubaer** [trusthlt/mining-legal-arguments#4]
Hi, I was going through this repo and the corresponding paper. In section 3.2.3 Data Analysis, it is mentioned "Additionally, we collected statistics about our gold data in general and for the arguments on the argument level as well as on the BIO-tag level."

Based on this I was wondering do we happen to have the annotation of the argument type on the sentence level (or can also a chunk of words are labeled as one of the argument types). As far as I could understand, currently, we have the annotation on the BIO level only.

Thanks in advance :)

**Comment by habernal** [comment]
Thanks for the question!

The minimal annotation unit was a token (we tokenized all paragraphs with Spacy 3.0.5), which means any sequence of tokens within a paragraph could have been annotated as an argument.

We didn't have any "sentences" pre-segmented.

Is that what you asked for?

I realized we didn't publish the full repository including the creation and annotation of the dataset yet, so it's something to be done (including the code for crawling and pre-processing the HUDOC cases)

**Comment by abdullahalzubaer** [comment]
Thanks for your response and clarification!

Yes, you are correct, that was what I was looking for. The reason was, to perform sentence level classification instead of token level, but I think it can be achieved (as you also pointed out) by converting the sequence of token label into a complete argument unit. 

I will close the issue since I believe my questions has been answered. 

Thank you for your work, which was quite interesting and valuable for the legal domain.
